<%@ page language="java" pageEncoding="UTF-8"%>
<!-- 表情 -->
<div class="face">
	<ul>
		<li><img src="${staticpath}/images/emoji/f000.gif" title="[呲牙]"></li>
        <li><img src="${staticpath}/images/emoji/f001.gif" title="[调皮]"></li>
        <li><img src="${staticpath}/images/emoji/f002.gif" title="[流汗]"></li>
        <li><img src="${staticpath}/images/emoji/f003.gif" title="[偷笑]"></li>
        <li><img src="${staticpath}/images/emoji/f004.gif" title="[再见]"></li>
        <li><img src="${staticpath}/images/emoji/f005.gif" title="[敲打]"></li>
        <li><img src="${staticpath}/images/emoji/f006.gif" title="[擦汗]"></li>
        <li><img src="${staticpath}/images/emoji/f007.gif" title="[猪头]"></li>
        <li><img src="${staticpath}/images/emoji/f008.gif" title="[玫瑰]"></li>
        <li><img src="${staticpath}/images/emoji/f009.gif" title="[流泪]"></li>
        <li><img src="${staticpath}/images/emoji/f010.gif" title="[大哭]"></li>
        <li><img src="${staticpath}/images/emoji/f011.gif" title="[嘘]"></li>
        <li><img src="${staticpath}/images/emoji/f012.gif" title="[酷]"></li>
        <li><img src="${staticpath}/images/emoji/f013.gif" title="[抓狂]"></li>
        <li><img src="${staticpath}/images/emoji/f014.gif" title="[委屈]"></li>
        <li><img src="${staticpath}/images/emoji/f015.gif" title="[便便]"></li>
        <li><img src="${staticpath}/images/emoji/f016.gif" title="[炸弹]"></li>
        <li><img src="${staticpath}/images/emoji/f017.gif" title="[菜刀]"></li>
        <li><img src="${staticpath}/images/emoji/f018.gif" title="[可爱]"></li>
        <li><img src="${staticpath}/images/emoji/f019.gif" title="[色]"></li>
        <li><img src="${staticpath}/images/emoji/f020.gif" title="[害羞]"></li>
        <li><img src="${staticpath}/images/emoji/f021.gif" title="[得意]"></li>
        <li><img src="${staticpath}/images/emoji/f022.gif" title="[吐]"></li>
        <li><img src="${staticpath}/images/emoji/f023.gif" title="[微笑]"></li>
        <li><img src="${staticpath}/images/emoji/f024.gif" title="[发怒]"></li>
        <li><img src="${staticpath}/images/emoji/f025.gif" title="[尴尬]"></li>
        <li><img src="${staticpath}/images/emoji/f026.gif" title="[惊恐]"></li>
        <li><img src="${staticpath}/images/emoji/f027.gif" title="[冷汗]"></li>
        <li><img src="${staticpath}/images/emoji/f028.gif" title="[爱心]"></li>
        <li><img src="${staticpath}/images/emoji/f029.gif" title="[示爱]"></li>
        <li><img src="${staticpath}/images/emoji/f030.gif" title="[白眼]"></li>
        <li><img src="${staticpath}/images/emoji/f031.gif" title="[傲慢]"></li>
        <li><img src="${staticpath}/images/emoji/f032.gif" title="[难过]"></li>
        <li><img src="${staticpath}/images/emoji/f033.gif" title="[惊讶]"></li>
        <li><img src="${staticpath}/images/emoji/f034.gif" title="[疑问]"></li>
        <li><img src="${staticpath}/images/emoji/f035.gif" title="[睡]"></li>
        <li><img src="${staticpath}/images/emoji/f036.gif" title="[亲亲]"></li>
        <li><img src="${staticpath}/images/emoji/f037.gif" title="[憨笑]"></li>
        <li><img src="${staticpath}/images/emoji/f038.gif" title="[爱情]"></li>
        <li><img src="${staticpath}/images/emoji/f039.gif" title="[衰]"></li>
        <li><img src="${staticpath}/images/emoji/f040.gif" title="[撇嘴]"></li>
        <li><img src="${staticpath}/images/emoji/f041.gif" title="[阴险]"></li>
        <li><img src="${staticpath}/images/emoji/f042.gif" title="[奋斗]"></li>
        <li><img src="${staticpath}/images/emoji/f043.gif" title="[发呆]"></li>
        <li><img src="${staticpath}/images/emoji/f044.gif" title="[右哼哼]"></li>
        <li><img src="${staticpath}/images/emoji/f045.gif" title="[拥抱]"></li>
        <li><img src="${staticpath}/images/emoji/f046.gif" title="[坏笑]"></li>
        <li><img src="${staticpath}/images/emoji/f047.gif" title="[飞吻]"></li>
        <li><img src="${staticpath}/images/emoji/f048.gif" title="[鄙视]"></li>
        <li><img src="${staticpath}/images/emoji/f049.gif" title="[晕]"></li>
        <li><img src="${staticpath}/images/emoji/f050.gif" title="[大兵]"></li>
        <li><img src="${staticpath}/images/emoji/f051.gif" title="[可怜]"></li>
        <li><img src="${staticpath}/images/emoji/f052.gif" title="[强]"></li>
        <li><img src="${staticpath}/images/emoji/f053.gif" title="[弱]"></li>
        <li><img src="${staticpath}/images/emoji/f054.gif" title="[握手]"></li>
        <li><img src="${staticpath}/images/emoji/f055.gif" title="[胜利]"></li>
        <li><img src="${staticpath}/images/emoji/f056.gif" title="[抱拳]"></li>
        <li><img src="${staticpath}/images/emoji/f057.gif" title="[凋谢]"></li>
        <li><img src="${staticpath}/images/emoji/f058.gif" title="[饭]"></li>
        <li><img src="${staticpath}/images/emoji/f059.gif" title="[蛋糕]"></li>
        <li><img src="${staticpath}/images/emoji/f060.gif" title="[西瓜]"></li>
        <li><img src="${staticpath}/images/emoji/f061.gif" title="[啤酒]"></li>
        <li><img src="${staticpath}/images/emoji/f062.gif" title="[飘虫]"></li>
        <li><img src="${staticpath}/images/emoji/f063.gif" title="[勾引]"></li>
        <li><img src="${staticpath}/images/emoji/f064.gif" title="[OK]"></li>
        <li><img src="${staticpath}/images/emoji/f065.gif" title="[爱你]"></li>
        <li><img src="${staticpath}/images/emoji/f066.gif" title="[咖啡]"></li>
        <li><img src="${staticpath}/images/emoji/f067.gif" title="[钱]"></li>
        <li><img src="${staticpath}/images/emoji/f068.gif" title="[月亮]"></li>
        <li><img src="${staticpath}/images/emoji/f069.gif" title="[美女]"></li>
        <li><img src="${staticpath}/images/emoji/f070.gif" title="[刀]"></li>
        <li><img src="${staticpath}/images/emoji/f071.gif" title="[发抖]"></li>
        <li><img src="${staticpath}/images/emoji/f072.gif" title="[差劲]"></li>
        <li><img src="${staticpath}/images/emoji/f073.gif" title="[拳头]"></li>
        <li><img src="${staticpath}/images/emoji/f074.gif" title="[心碎]"></li>
        <li><img src="${staticpath}/images/emoji/f075.gif" title="[太阳]"></li>
        <li><img src="${staticpath}/images/emoji/f076.gif" title="[礼物]"></li>
        <li><img src="${staticpath}/images/emoji/f077.gif" title="[足球]"></li>
        <li><img src="${staticpath}/images/emoji/f078.gif" title="[骷髅]"></li>
        <li><img src="${staticpath}/images/emoji/f079.gif" title="[挥手]"></li>
        <li><img src="${staticpath}/images/emoji/f080.gif" title="[闪电]"></li>
        <li><img src="${staticpath}/images/emoji/f081.gif" title="[饥饿]"></li>
        <li><img src="${staticpath}/images/emoji/f082.gif" title="[困]"></li>
        <li><img src="${staticpath}/images/emoji/f083.gif" title="[咒骂]"></li>
        <li><img src="${staticpath}/images/emoji/f084.gif" title="[折磨]"></li>
        <li><img src="${staticpath}/images/emoji/f085.gif" title="[抠鼻]"></li>
        <li><img src="${staticpath}/images/emoji/f086.gif" title="[鼓掌]"></li>
        <li><img src="${staticpath}/images/emoji/f087.gif" title="[糗大了]"></li>
        <li><img src="${staticpath}/images/emoji/f088.gif" title="[左哼哼]"></li>
        <li><img src="${staticpath}/images/emoji/f089.gif" title="[哈欠]"></li>
        <li><img src="${staticpath}/images/emoji/f090.gif" title="[快哭了]"></li>
        <li><img src="${staticpath}/images/emoji/f091.gif" title="[吓]"></li>
        <li><img src="${staticpath}/images/emoji/f092.gif" title="[篮球]"></li>
        <li><img src="${staticpath}/images/emoji/f093.gif" title="[乒乓球]"></li>
        <li><img src="${staticpath}/images/emoji/f094.gif" title="[NO]"></li>
        <li><img src="${staticpath}/images/emoji/f095.gif" title="[跳跳]"></li>
        <li><img src="${staticpath}/images/emoji/f096.gif" title="[怄火]"></li>
        <li><img src="${staticpath}/images/emoji/f097.gif" title="[转圈]"></li>
        <li><img src="${staticpath}/images/emoji/f098.gif" title="[磕头]"></li>
        <li><img src="${staticpath}/images/emoji/f099.gif" title="[回头]"></li>
        <li><img src="${staticpath}/images/emoji/f100.gif" title="[跳绳]"></li>
        <li><img src="${staticpath}/images/emoji/f101.gif" title="[激动]"></li>
        <li><img src="${staticpath}/images/emoji/f102.gif" title="[街舞]"></li>
        <li><img src="${staticpath}/images/emoji/f103.gif" title="[献吻]"></li>
        <li><img src="${staticpath}/images/emoji/f104.gif" title="[左太极]"></li>
        <li><img src="${staticpath}/images/emoji/f105.gif" title="[右太极]"></li>
        <li><img src="${staticpath}/images/emoji/f106.gif" title="[闭嘴]"></li>
	</ul>
</div>